More char stats
Zshuff03/ARPG-TD pull request #12
Opened 2018-07-04 15:42 UTC by Axxis05

putting this on hold where i'm at for now. will need tweaks later after interactions are in place

2018-07-05 22:51 UTC, Zshuff03 requested changes

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Character.cs
> +        for(int i=0; i<6; i++){
What's this magic number? try to avoid random numbers like this. Also, you said things are going to be changed right?

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Experience.cs
> +    public int lvl;
try to use good descriptors, `lvl` is too generic of a variable, maybe do charLevel?

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Experience.cs
> +        expToNext = 500 + 0.4 * (100 * curLvl * curLvl);
more magic numbers, dont do that

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Inventory.cs
> +	void Start () {
Why is there 2 files that do almost identical things?

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Inventory.cs
> +				Stats charStats = transform.GetComponent<Stats>();
whats with the indentation here?

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Inventory.cs
> +        for(int i=0; i<6; i++){
this '6' is appearing everywhere. I'm guessing it's the inventory slots but that's not obvious, make it a variable

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Inventory.cs
> +					charStats.Intillect.AddModifier(new StatModifier(stats[2], StatModType.Flat, 0, inventory[i]));
intellect *

2018-07-05 22:51 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Stats.cs
> +	NavMeshAgent pc;
whats a `pc` and why is there a stats script and stats on the character script?

2018-07-06 21:30 UTC, Zshuff03 reviewed
There's a few more spots where you can add spaces between brackets and shit, I'm going to stop being annoyed by it I guess.  If you want to look deeper into and try and find a linter so your editor will tell you when you are missing shit like that go for it. Once you fix these small things go ahead and merge this

2018-07-06 21:30 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Stats.cs
> +    public CharacterStat Intillect;
Intellect*

2018-07-06 21:30 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Experience.cs
> +	void Start(){
Well I looked for a linter, but apparently c# developers are too good to have their code tell them it's formatted wrong so I'm going to be spamming you with changes so our code looks the same.

Space between Start() and {

2018-07-06 21:30 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Experience.cs
> +	public double calcNextLevel(double curLvl){
space between bracket and function

2018-07-06 21:30 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Experience.cs
> +    public void gainExp(int expGained){
space between bracket and function

2018-07-06 21:30 UTC, Zshuff03 commented on Assets/PlayerAssets/Scripts/Experience.cs
> +        }else{
space between bracket and function

2018-07-08 00:03 UTC, Axxis05 commented
Corrected all brackets and spelling

2018-07-08 00:04 UTC, merged